version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    container_name: todo-frontend
    ports:
      - '3000:3000'
    networks:
      - todo-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  backend:
    build:
      context: ./backend
    container_name: todo-backend
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/todo
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: todo-mongodb
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo-data: